//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CryptoServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CryptoStr", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CryptoStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        private int SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((this.SourceString1Field.Equals(value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Str256", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Str256 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SourceString1Field, value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptoServiceReference1.CryptoServiceSoap")]
    public interface CryptoServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference1.EncryptResponse Encrypt(ServiceClient.CryptoServiceReference1.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.EncryptResponse> EncryptAsync(ServiceClient.CryptoServiceReference1.EncryptRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Decrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference1.DecryptResponse Decrypt(ServiceClient.CryptoServiceReference1.DecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Decrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.DecryptResponse> DecryptAsync(ServiceClient.CryptoServiceReference1.DecryptRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumMass", ReplyAction="*")]
        ServiceClient.CryptoServiceReference1.SumMassResponse SumMass(ServiceClient.CryptoServiceReference1.SumMassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumMass", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.SumMassResponse> SumMassAsync(ServiceClient.CryptoServiceReference1.SumMassRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.EncryptRequestBody Body;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(ServiceClient.CryptoServiceReference1.EncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.CryptoStr str;
        
        public EncryptRequestBody() {
        }
        
        public EncryptRequestBody(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.EncryptResponseBody Body;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(ServiceClient.CryptoServiceReference1.EncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.CryptoStr EncryptResult;
        
        public EncryptResponseBody() {
        }
        
        public EncryptResponseBody(ServiceClient.CryptoServiceReference1.CryptoStr EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Decrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.DecryptRequestBody Body;
        
        public DecryptRequest() {
        }
        
        public DecryptRequest(ServiceClient.CryptoServiceReference1.DecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.CryptoStr str;
        
        public DecryptRequestBody() {
        }
        
        public DecryptRequestBody(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.DecryptResponseBody Body;
        
        public DecryptResponse() {
        }
        
        public DecryptResponse(ServiceClient.CryptoServiceReference1.DecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.CryptoStr DecryptResult;
        
        public DecryptResponseBody() {
        }
        
        public DecryptResponseBody(ServiceClient.CryptoServiceReference1.CryptoStr DecryptResult) {
            this.DecryptResult = DecryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumMassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumMass", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.SumMassRequestBody Body;
        
        public SumMassRequest() {
        }
        
        public SumMassRequest(ServiceClient.CryptoServiceReference1.SumMassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumMassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.Str256 str;
        
        public SumMassRequestBody() {
        }
        
        public SumMassRequestBody(ServiceClient.CryptoServiceReference1.Str256 str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumMassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumMassResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference1.SumMassResponseBody Body;
        
        public SumMassResponse() {
        }
        
        public SumMassResponse(ServiceClient.CryptoServiceReference1.SumMassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumMassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference1.Str256 SumMassResult;
        
        public SumMassResponseBody() {
        }
        
        public SumMassResponseBody(ServiceClient.CryptoServiceReference1.Str256 SumMassResult) {
            this.SumMassResult = SumMassResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CryptoServiceSoapChannel : ServiceClient.CryptoServiceReference1.CryptoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoServiceSoapClient : System.ServiceModel.ClientBase<ServiceClient.CryptoServiceReference1.CryptoServiceSoap>, ServiceClient.CryptoServiceReference1.CryptoServiceSoap {
        
        public CryptoServiceSoapClient() {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference1.EncryptResponse ServiceClient.CryptoServiceReference1.CryptoServiceSoap.Encrypt(ServiceClient.CryptoServiceReference1.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference1.CryptoStr Encrypt(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            ServiceClient.CryptoServiceReference1.EncryptRequest inValue = new ServiceClient.CryptoServiceReference1.EncryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.EncryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference1.EncryptResponse retVal = ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).Encrypt(inValue);
            return retVal.Body.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.EncryptResponse> ServiceClient.CryptoServiceReference1.CryptoServiceSoap.EncryptAsync(ServiceClient.CryptoServiceReference1.EncryptRequest request) {
            return base.Channel.EncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.EncryptResponse> EncryptAsync(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            ServiceClient.CryptoServiceReference1.EncryptRequest inValue = new ServiceClient.CryptoServiceReference1.EncryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.EncryptRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).EncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference1.DecryptResponse ServiceClient.CryptoServiceReference1.CryptoServiceSoap.Decrypt(ServiceClient.CryptoServiceReference1.DecryptRequest request) {
            return base.Channel.Decrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference1.CryptoStr Decrypt(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            ServiceClient.CryptoServiceReference1.DecryptRequest inValue = new ServiceClient.CryptoServiceReference1.DecryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.DecryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference1.DecryptResponse retVal = ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).Decrypt(inValue);
            return retVal.Body.DecryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.DecryptResponse> ServiceClient.CryptoServiceReference1.CryptoServiceSoap.DecryptAsync(ServiceClient.CryptoServiceReference1.DecryptRequest request) {
            return base.Channel.DecryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.DecryptResponse> DecryptAsync(ServiceClient.CryptoServiceReference1.CryptoStr str) {
            ServiceClient.CryptoServiceReference1.DecryptRequest inValue = new ServiceClient.CryptoServiceReference1.DecryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.DecryptRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).DecryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference1.SumMassResponse ServiceClient.CryptoServiceReference1.CryptoServiceSoap.SumMass(ServiceClient.CryptoServiceReference1.SumMassRequest request) {
            return base.Channel.SumMass(request);
        }
        
        public ServiceClient.CryptoServiceReference1.Str256 SumMass(ServiceClient.CryptoServiceReference1.Str256 str) {
            ServiceClient.CryptoServiceReference1.SumMassRequest inValue = new ServiceClient.CryptoServiceReference1.SumMassRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.SumMassRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference1.SumMassResponse retVal = ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).SumMass(inValue);
            return retVal.Body.SumMassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.SumMassResponse> ServiceClient.CryptoServiceReference1.CryptoServiceSoap.SumMassAsync(ServiceClient.CryptoServiceReference1.SumMassRequest request) {
            return base.Channel.SumMassAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference1.SumMassResponse> SumMassAsync(ServiceClient.CryptoServiceReference1.Str256 str) {
            ServiceClient.CryptoServiceReference1.SumMassRequest inValue = new ServiceClient.CryptoServiceReference1.SumMassRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference1.SumMassRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference1.CryptoServiceSoap)(this)).SumMassAsync(inValue);
        }
    }
}
