//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CryptoServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CryptoStr", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CryptoStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        private int SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((this.SourceString1Field.Equals(value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Str256", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Str256 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SourceString1Field, value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckMass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckMass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SourceString1Field, value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckStr", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceString1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString1 {
            get {
                return this.SourceString1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SourceString1Field, value) != true)) {
                    this.SourceString1Field = value;
                    this.RaisePropertyChanged("SourceString1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptoServiceReference3.CryptoServiceSoap")]
    public interface CryptoServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference3.EncryptResponse Encrypt(ServiceClient.CryptoServiceReference3.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.EncryptResponse> EncryptAsync(ServiceClient.CryptoServiceReference3.EncryptRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Decrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference3.DecryptResponse Decrypt(ServiceClient.CryptoServiceReference3.DecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Decrypt", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.DecryptResponse> DecryptAsync(ServiceClient.CryptoServiceReference3.DecryptRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumMass", ReplyAction="*")]
        ServiceClient.CryptoServiceReference3.SumMassResponse SumMass(ServiceClient.CryptoServiceReference3.SumMassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumMass", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.SumMassResponse> SumMassAsync(ServiceClient.CryptoServiceReference3.SumMassRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassCheck", ReplyAction="*")]
        ServiceClient.CryptoServiceReference3.MassCheckResponse MassCheck(ServiceClient.CryptoServiceReference3.MassCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.MassCheckResponse> MassCheckAsync(ServiceClient.CryptoServiceReference3.MassCheckRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем str из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrCheck", ReplyAction="*")]
        ServiceClient.CryptoServiceReference3.StrCheckResponse StrCheck(ServiceClient.CryptoServiceReference3.StrCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.StrCheckResponse> StrCheckAsync(ServiceClient.CryptoServiceReference3.StrCheckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.EncryptRequestBody Body;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(ServiceClient.CryptoServiceReference3.EncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CryptoStr str;
        
        public EncryptRequestBody() {
        }
        
        public EncryptRequestBody(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.EncryptResponseBody Body;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(ServiceClient.CryptoServiceReference3.EncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CryptoStr EncryptResult;
        
        public EncryptResponseBody() {
        }
        
        public EncryptResponseBody(ServiceClient.CryptoServiceReference3.CryptoStr EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Decrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.DecryptRequestBody Body;
        
        public DecryptRequest() {
        }
        
        public DecryptRequest(ServiceClient.CryptoServiceReference3.DecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CryptoStr str;
        
        public DecryptRequestBody() {
        }
        
        public DecryptRequestBody(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.DecryptResponseBody Body;
        
        public DecryptResponse() {
        }
        
        public DecryptResponse(ServiceClient.CryptoServiceReference3.DecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CryptoStr DecryptResult;
        
        public DecryptResponseBody() {
        }
        
        public DecryptResponseBody(ServiceClient.CryptoServiceReference3.CryptoStr DecryptResult) {
            this.DecryptResult = DecryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumMassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumMass", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.SumMassRequestBody Body;
        
        public SumMassRequest() {
        }
        
        public SumMassRequest(ServiceClient.CryptoServiceReference3.SumMassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumMassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.Str256 str;
        
        public SumMassRequestBody() {
        }
        
        public SumMassRequestBody(ServiceClient.CryptoServiceReference3.Str256 str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumMassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumMassResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.SumMassResponseBody Body;
        
        public SumMassResponse() {
        }
        
        public SumMassResponse(ServiceClient.CryptoServiceReference3.SumMassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumMassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.Str256 SumMassResult;
        
        public SumMassResponseBody() {
        }
        
        public SumMassResponseBody(ServiceClient.CryptoServiceReference3.Str256 SumMassResult) {
            this.SumMassResult = SumMassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MassCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MassCheck", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.MassCheckRequestBody Body;
        
        public MassCheckRequest() {
        }
        
        public MassCheckRequest(ServiceClient.CryptoServiceReference3.MassCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MassCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CheckMass str;
        
        public MassCheckRequestBody() {
        }
        
        public MassCheckRequestBody(ServiceClient.CryptoServiceReference3.CheckMass str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MassCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MassCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.MassCheckResponseBody Body;
        
        public MassCheckResponse() {
        }
        
        public MassCheckResponse(ServiceClient.CryptoServiceReference3.MassCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MassCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CheckMass MassCheckResult;
        
        public MassCheckResponseBody() {
        }
        
        public MassCheckResponseBody(ServiceClient.CryptoServiceReference3.CheckMass MassCheckResult) {
            this.MassCheckResult = MassCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrCheck", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.StrCheckRequestBody Body;
        
        public StrCheckRequest() {
        }
        
        public StrCheckRequest(ServiceClient.CryptoServiceReference3.StrCheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrCheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CheckStr str;
        
        public StrCheckRequestBody() {
        }
        
        public StrCheckRequestBody(ServiceClient.CryptoServiceReference3.CheckStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrCheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference3.StrCheckResponseBody Body;
        
        public StrCheckResponse() {
        }
        
        public StrCheckResponse(ServiceClient.CryptoServiceReference3.StrCheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrCheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference3.CheckStr StrCheckResult;
        
        public StrCheckResponseBody() {
        }
        
        public StrCheckResponseBody(ServiceClient.CryptoServiceReference3.CheckStr StrCheckResult) {
            this.StrCheckResult = StrCheckResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CryptoServiceSoapChannel : ServiceClient.CryptoServiceReference3.CryptoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoServiceSoapClient : System.ServiceModel.ClientBase<ServiceClient.CryptoServiceReference3.CryptoServiceSoap>, ServiceClient.CryptoServiceReference3.CryptoServiceSoap {
        
        public CryptoServiceSoapClient() {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference3.EncryptResponse ServiceClient.CryptoServiceReference3.CryptoServiceSoap.Encrypt(ServiceClient.CryptoServiceReference3.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference3.CryptoStr Encrypt(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            ServiceClient.CryptoServiceReference3.EncryptRequest inValue = new ServiceClient.CryptoServiceReference3.EncryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.EncryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference3.EncryptResponse retVal = ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).Encrypt(inValue);
            return retVal.Body.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.EncryptResponse> ServiceClient.CryptoServiceReference3.CryptoServiceSoap.EncryptAsync(ServiceClient.CryptoServiceReference3.EncryptRequest request) {
            return base.Channel.EncryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.EncryptResponse> EncryptAsync(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            ServiceClient.CryptoServiceReference3.EncryptRequest inValue = new ServiceClient.CryptoServiceReference3.EncryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.EncryptRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).EncryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference3.DecryptResponse ServiceClient.CryptoServiceReference3.CryptoServiceSoap.Decrypt(ServiceClient.CryptoServiceReference3.DecryptRequest request) {
            return base.Channel.Decrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference3.CryptoStr Decrypt(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            ServiceClient.CryptoServiceReference3.DecryptRequest inValue = new ServiceClient.CryptoServiceReference3.DecryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.DecryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference3.DecryptResponse retVal = ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).Decrypt(inValue);
            return retVal.Body.DecryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.DecryptResponse> ServiceClient.CryptoServiceReference3.CryptoServiceSoap.DecryptAsync(ServiceClient.CryptoServiceReference3.DecryptRequest request) {
            return base.Channel.DecryptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.DecryptResponse> DecryptAsync(ServiceClient.CryptoServiceReference3.CryptoStr str) {
            ServiceClient.CryptoServiceReference3.DecryptRequest inValue = new ServiceClient.CryptoServiceReference3.DecryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.DecryptRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).DecryptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference3.SumMassResponse ServiceClient.CryptoServiceReference3.CryptoServiceSoap.SumMass(ServiceClient.CryptoServiceReference3.SumMassRequest request) {
            return base.Channel.SumMass(request);
        }
        
        public ServiceClient.CryptoServiceReference3.Str256 SumMass(ServiceClient.CryptoServiceReference3.Str256 str) {
            ServiceClient.CryptoServiceReference3.SumMassRequest inValue = new ServiceClient.CryptoServiceReference3.SumMassRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.SumMassRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference3.SumMassResponse retVal = ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).SumMass(inValue);
            return retVal.Body.SumMassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.SumMassResponse> ServiceClient.CryptoServiceReference3.CryptoServiceSoap.SumMassAsync(ServiceClient.CryptoServiceReference3.SumMassRequest request) {
            return base.Channel.SumMassAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.SumMassResponse> SumMassAsync(ServiceClient.CryptoServiceReference3.Str256 str) {
            ServiceClient.CryptoServiceReference3.SumMassRequest inValue = new ServiceClient.CryptoServiceReference3.SumMassRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.SumMassRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).SumMassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference3.MassCheckResponse ServiceClient.CryptoServiceReference3.CryptoServiceSoap.MassCheck(ServiceClient.CryptoServiceReference3.MassCheckRequest request) {
            return base.Channel.MassCheck(request);
        }
        
        public ServiceClient.CryptoServiceReference3.CheckMass MassCheck(ServiceClient.CryptoServiceReference3.CheckMass str) {
            ServiceClient.CryptoServiceReference3.MassCheckRequest inValue = new ServiceClient.CryptoServiceReference3.MassCheckRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.MassCheckRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference3.MassCheckResponse retVal = ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).MassCheck(inValue);
            return retVal.Body.MassCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.MassCheckResponse> ServiceClient.CryptoServiceReference3.CryptoServiceSoap.MassCheckAsync(ServiceClient.CryptoServiceReference3.MassCheckRequest request) {
            return base.Channel.MassCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.MassCheckResponse> MassCheckAsync(ServiceClient.CryptoServiceReference3.CheckMass str) {
            ServiceClient.CryptoServiceReference3.MassCheckRequest inValue = new ServiceClient.CryptoServiceReference3.MassCheckRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.MassCheckRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).MassCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference3.StrCheckResponse ServiceClient.CryptoServiceReference3.CryptoServiceSoap.StrCheck(ServiceClient.CryptoServiceReference3.StrCheckRequest request) {
            return base.Channel.StrCheck(request);
        }
        
        public ServiceClient.CryptoServiceReference3.CheckStr StrCheck(ServiceClient.CryptoServiceReference3.CheckStr str) {
            ServiceClient.CryptoServiceReference3.StrCheckRequest inValue = new ServiceClient.CryptoServiceReference3.StrCheckRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.StrCheckRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference3.StrCheckResponse retVal = ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).StrCheck(inValue);
            return retVal.Body.StrCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.StrCheckResponse> ServiceClient.CryptoServiceReference3.CryptoServiceSoap.StrCheckAsync(ServiceClient.CryptoServiceReference3.StrCheckRequest request) {
            return base.Channel.StrCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CryptoServiceReference3.StrCheckResponse> StrCheckAsync(ServiceClient.CryptoServiceReference3.CheckStr str) {
            ServiceClient.CryptoServiceReference3.StrCheckRequest inValue = new ServiceClient.CryptoServiceReference3.StrCheckRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference3.StrCheckRequestBody();
            inValue.Body.str = str;
            return ((ServiceClient.CryptoServiceReference3.CryptoServiceSoap)(this)).StrCheckAsync(inValue);
        }
    }
}
